import birukPortrait from '@/assets/team/team-biruk.svg';
import dejenePortrait from '@/assets/team/team-dejene.svg';
import tegenPortrait from '@/assets/team/team-tegen.svg';
import samuelPortrait from '@/assets/team/team-samuel.svg';
import esubalewPortrait from '@/assets/team/team-esubalew.svg';
import abebePortrait from '@/assets/team/team-abebe.svg';

export type ContentPage = { title: string; eyebrow: string; intro: string; sections: { title: string; body: string }[]; image?: 'solar' | 'farm' | 'data' | 'landscape' };
export const pages: Record<string, ContentPage> = {
  about: {title:'Turning climate challenges into practical solutions',eyebrow:'About Africa Climate Actions',intro:'We connect science, engineering, finance, digital technologies, local knowledge, and partnerships to develop practical climate solutions for Africa.', image:'landscape',sections:[
    {title:'Our mission',body:"To develop and scale practical climate solutions that reduce emissions, strengthen resilience, create economic opportunities, and support Africa’s transition toward sustainable development."},
    {title:'Our vision',body:'An Africa where climate action supports cleaner energy, productive agriculture, resilient communities, competitive businesses, and inclusive economic growth.'},
    {title:'How we work',body:'We work from early concept development through feasibility, financing, implementation, monitoring, reporting, and scaling. Where appropriate, we connect projects with greenhouse gas inventories, Nationally Determined Contributions, carbon markets, climate finance, and national development priorities.'}]},
  services:{title:'Services for climate investment and implementation',eyebrow:'Our solutions',intro:'Technical expertise. Investment readiness. Practical implementation. We bring the capabilities together to move climate projects forward.',image:'solar',sections:[
    {title:'Climate advisory and project development',body:'Our services include climate strategy, feasibility assessment, project design, technical studies, investment planning, business modelling, emissions assessment, climate finance preparation, and implementation planning.'},
    {title:'Renewable energy and biogas',body:'Our services include site assessment, system design, technology selection, procurement support, installation, commissioning, operation planning, performance monitoring, and technical capacity building. Biogas systems convert livestock manure and other organic waste into renewable energy while producing nutrient-rich digestate.'},
    {title:'Circular agriculture and resource recovery',body:'We help clients convert agricultural waste into energy, fertilizer, feed-related resources, and other productive inputs. Our approach connects livestock, manure management, renewable energy, fertilizer production, forage production, crop production, and waste recovery.'},
    {title:'Climate-smart agriculture',body:'Areas of work include improved manure management, renewable energy integration, nutrient recycling, forage production, soil management, low-emission livestock systems, water efficiency, and climate-resilient agricultural technologies.'},
    {title:'Carbon markets and climate finance',body:'Our support can include project screening, greenhouse gas baseline development, emissions reduction calculations, monitoring design, carbon project documentation, financial modelling, investor engagement, climate finance preparation, and carbon revenue assessment.'},
    {title:'Digital MRV and climate data',body:'We develop digital solutions for greenhouse gas inventories, NDC tracking, field data collection, emissions calculations, reporting, verification, and climate investment decision support.'}]},
  projects:{title:'From climate ideas to working solutions',eyebrow:'Projects',intro:'Our work brings energy, agriculture, climate finance, engineering, and digital systems together. We focus on projects that can produce measurable climate benefits alongside economic and social value.',image:'farm',sections:[
    {title:'Integrated Biogas, Forage and Dairy Circular Economy Project',body:'In Furi, Sheger City, Ethiopia, Africa Climate Actions PLC is advancing an integrated circular agriculture concept connecting livestock production, renewable energy, organic fertilizer, forage production, and clean transport energy.'},
    {title:'Agricultural biogas systems',body:'We support the design and implementation of biogas systems that convert livestock manure and agricultural waste into useful energy and fertilizer. Projects can include household, farm, cooperative, institutional, and commercial systems.'},
    {title:'Digital MRV for climate projects',body:'We develop monitoring systems that allow climate projects to collect field data, calculate emissions reductions, monitor technology performance, and prepare evidence for reporting and verification.'},
    {title:'Climate-smart livestock',body:'Our work connects feeding, manure management, renewable energy, forage production, greenhouse gas accounting, and climate finance to improve productivity and resource efficiency.'},
    {title:'Carbon project development',body:'Potential project areas include renewable energy, waste management, agriculture, livestock, soil management, and circular resource systems.'}]},
  'featured-project':{title:'Integrated Biogas, Forage and Dairy Circular Economy Project',eyebrow:'Featured concept · Furi, Sheger City, Ethiopia',intro:'Turning livestock manure into a productive resource. An integrated concept connecting cleaner energy, organic fertilizer, forage, and dairy production.',image:'farm',sections:[
    {title:'From manure to energy',body:'Anaerobic digestion converts livestock manure into renewable biogas. Instead of releasing methane from unmanaged manure, the system captures its energy value. Depending on scale and technical configuration, cleaned biogas can support cooking, heating, electricity generation, industrial energy use, or transport applications.'},
    {title:'From digestate to agricultural production',body:'Biogas production generates digestate containing plant nutrients and organic matter. With proper treatment and management, this material can be used as organic fertilizer. The project links digestate recycling with forage production, returning nutrients to the agricultural system.'},
    {title:'A model for circular agriculture',body:'The concept can be adapted for dairy clusters, livestock production areas, municipalities, cooperatives, commercial farms, and agro-industrial systems across Africa. Potential benefits include reduced methane emissions, renewable energy, nutrient recycling, improved manure management, and new business and carbon finance opportunities.'}]},
  'digital-mrv':{title:'Climate data you can measure, use and trust',eyebrow:'Digital MRV & climate intelligence',intro:'Our digital measurement, reporting, and verification approach connects field activities with greenhouse gas calculations, dashboards, reporting, and verification.',image:'data',sections:[
    {title:'From field data to climate results',body:'Digital field data collection, sensor integration, technology performance data, activity data management, greenhouse gas calculations, baseline comparison, emissions reduction estimation, carbon project monitoring, NDC indicators, data quality checks, analytics, and verification-ready reports.'},
    {title:'Supporting national climate systems',body:'We support approaches that connect local project information with national greenhouse gas inventories and NDC monitoring systems. This can help improve data quality, reduce reporting gaps, strengthen institutional ownership, and make climate investments easier to track.'},
    {title:'Artificial intelligence and climate analytics',body:'We explore artificial intelligence, digital tools, sensors, and data analytics for emissions estimation, anomaly detection, technology performance monitoring, agricultural decision support, data quality assessment, and climate investment analysis.'}]},
  'carbon-markets':{title:'Turning climate performance into finance',eyebrow:'Carbon markets & climate finance',intro:'We help clients move from climate project concepts toward measurable and finance-ready opportunities.',image:'solar',sections:[
    {title:'Investment built on credible evidence',body:'Our services can include project screening, baseline assessment, greenhouse gas calculations, monitoring systems, carbon methodology assessment, project finance modelling, and market readiness.'},
    {title:'Beyond carbon credits',body:'We assess projects based on technical performance, revenue potential, operating costs, climate benefits, social value, and opportunities for scaling. Carbon revenue can become one component within a stronger overall business model.'}]},
  'climate-business-models':{title:'Building businesses around climate solutions',eyebrow:'Climate business models',intro:'We support entrepreneurs, businesses, investors, public institutions, and development partners in developing commercial models around climate technologies.',image:'farm',sections:[
    {title:'Energy and circular resources',body:'Renewable energy, biogas, organic fertilizer, circular agriculture, resource recovery, waste management, and electric mobility.'},
    {title:'Climate-smart production',body:'Climate-smart livestock, climate-smart agriculture, and low-emission production systems.'},
    {title:'Digital and carbon services',body:'Digital climate services, carbon project services, greenhouse gas data systems, and climate analytics.'}]},
  partners:{title:'People. Partnerships. Resilient Africa.',eyebrow:'Partnerships & engagement',intro:'Practical climate solutions bring public institutions, research organizations, development partners, businesses, and communities together.',sections:[
    {title:'Ethiopian Ministry of Agriculture',body:'Supporting collaboration around climate-smart agriculture, livestock development, manure management, renewable energy, greenhouse gas mitigation, and agricultural transformation.'},
    {title:'Ethiopian Ministry of Planning and Development',body:'Supporting collaboration related to climate planning, national development priorities, greenhouse gas reporting, NDC implementation, and climate investment.'},
    {title:'Wolaita Sodo University',body:'Academic and research collaboration supporting knowledge generation, technology evaluation, capacity development, and applied climate solutions.'},
    {title:'International Livestock Research Institute (ILRI)',body:'Collaboration related to livestock systems, greenhouse gas measurement, manure management, biogas, agricultural research, emissions data, and climate solutions for livestock production.'},
    {title:'World Bank',body:'Engagement around climate-resilient development, investment, agriculture, infrastructure, climate finance, and sustainable development.'},
    {title:'United Nations Development Programme (UNDP)',body:'Collaboration opportunities around climate action, development, climate finance, institutional capacity, and sustainable investment.'},
    {title:'United Nations Environment Programme (UNEP)',body:'Engagement around environmental sustainability, climate mitigation, resource efficiency, pollution reduction, and climate-related development.'}]},
  impact:{title:'Climate action with measurable results',eyebrow:'Our impact priorities',intro:'Our goal is to create climate solutions that produce results beyond emissions reductions, supporting energy access, agricultural productivity, resource efficiency, employment, food systems, and local economic development.',image:'landscape',sections:[
    {title:'Cleaner energy and lower emissions',body:'Cleaner energy, reduced greenhouse gas emissions, and better manure and waste management.'},
    {title:'Productive, circular agriculture',body:'Improved agricultural productivity, circular use of agricultural resources, and resilient communities.'},
    {title:'Evidence and investment',body:'Stronger climate data, improved climate investment decisions, climate finance mobilization, new green businesses, and stronger institutional capacity.'}]},
  'why-africa-climate-actions':{title:'Local understanding. Global climate ambition.',eyebrow:'Why Africa Climate Actions',intro:'Africa requires climate solutions designed around its own production systems, institutions, markets, resources, and development priorities.',image:'landscape',sections:[
    {title:'Connected capabilities',body:'We combine local implementation experience with international climate methods, digital technologies, engineering, science, and finance.'},
    {title:'Practical by design',body:'Our role is to connect these capabilities and turn them into practical projects. Climate action should result in functioning technologies, stronger enterprises, better use of resources, new investment opportunities, and improved livelihoods.'}]},
  contact:{title:'Build the next climate solution with us',eyebrow:'Let’s work together',intro:'Contact us to discuss partnerships, project development, renewable energy, climate-smart agriculture, carbon markets, climate finance, digital MRV, and related advisory services.',sections:[
    {title:'Visit our office',body:'Nefas Silk Lafto Sub City, Woreda 01, Addis Ababa, Ethiopia'},
    {title:'Telephone',body:'+251 923 275 050'},
    {title:'Chief Executive Officer',body:'Dr Biruk Alemu'}]},
  privacy:{title:'Website privacy notice',eyebrow:'Privacy & personal information',intro:'Africa Climate Actions PLC respects the privacy of website visitors, clients, partners, project participants, and other individuals whose personal information is handled through our website and business activities.',sections:[
    {title:'Information we may collect',body:'We may collect information you choose to provide, including your name, email address, telephone number, organization, job title, and information submitted through contact, partnership, recruitment, or project enquiry forms. We may also collect basic website usage information needed to operate, secure, and improve the website.'},
    {title:'How we use information',body:'We may use personal information to respond to enquiries, manage business and partnership relationships, provide requested information, administer projects, communicate about relevant activities, improve our services, and meet applicable legal and regulatory requirements.'},
    {title:'How we protect information',body:'We take reasonable organizational and technical measures to protect personal information from unauthorized access, loss, misuse, alteration, or disclosure.'},
    {title:'Sharing of information',body:'We do not sell personal information. Information may be shared with service providers, professional advisers, project partners, or public authorities when necessary for a stated business purpose, contractual requirement, or legal obligation. Where appropriate, reasonable safeguards will be applied.'},
    {title:'Data retention',body:'Personal information will be retained only for as long as reasonably necessary for the purpose for which it was collected, for legitimate business needs, or as required by applicable law.'},
    {title:'Your choices and rights',body:'You may contact Africa Climate Actions PLC to ask about personal information held about you and to request correction, deletion, or other action where applicable under relevant law.'},
    {title:'Cookies and website technologies',body:'The website may use cookies or similar technologies necessary for operation, security, analytics, and user experience. Where consent is required, visitors should be given an appropriate choice before optional cookies are used.'},
    {title:'External links',body:'The website may contain links to external websites. Africa Climate Actions PLC is not responsible for the privacy practices or content of websites operated by other organizations.'},
    {title:'Changes to this notice',body:'This privacy notice may be updated when our services, website practices, or legal requirements change. The current version should be published on the company website with its effective date.'},
    {title:'Privacy contact',body:'For questions about this privacy notice or the handling of personal information, contact Africa Climate Actions PLC at Nefas Silk Lafto Sub City, Woreda 01, Addis Ababa, Ethiopia, telephone +251 923 275 050.'},
    {title:'Draft notice',body:'This privacy notice is a website draft and should be reviewed against current Ethiopian legal requirements and the company’s actual data-handling practices before final publication.'}]}
};
export const team = [
 ['Dr Biruk Alemu','Chief Executive Officer','Provides overall leadership, including corporate strategy, partnerships, project development, client engagement, and company growth.'],
 ['Dr Dejene Girma','Climate Mitigation, Renewable Energy and Carbon Market Finance','Leads technical work related to climate mitigation, renewable energy solutions, carbon markets, and climate finance.'],
 ['Dr Tegen Cherinet','Senior Expert in Climate Smart Agriculture','Supports resilient and resource-efficient climate-smart agricultural production.'],
 ['Dr Samuel Ayalew','AI Expert','Supports artificial intelligence, digital systems, and data analytics for climate, agriculture, energy, and MRV.'],
 ['Dr Esubalew Ayalew','Economist','Supports economic analysis, business modelling, investment assessment, and evaluation of financial and development outcomes.'],
 ['Dr Abebe Bayu','Accounting and Finance','Supports accounting, financial management, budgeting, financial controls, and company finance functions.']
];
export const teamPortraits: Record<string, string> = {
  'Dr Biruk Alemu': birukPortrait,
  'Dr Dejene Girma': dejenePortrait,
  'Dr Tegen Cherinet': tegenPortrait,
  'Dr Samuel Ayalew': samuelPortrait,
  'Dr Esubalew Ayalew': esubalewPortrait,
  'Dr Abebe Bayu': abebePortrait,
};
export const cycleSteps = [
 ['Livestock','Dairy and livestock production begins the resource cycle.'],['Manure','Manure is collected and managed as a productive resource.'],['Biodigester','Anaerobic digestion converts organic matter into biogas and digestate.'],['Biogas','Captured gas can be cleaned and upgraded for productive uses.'],['Energy','Biogas can support heat, electricity, or potential transport fuel applications.'],['Digestate','The remaining material contains plant nutrients and organic matter.'],['Organic fertilizer','Properly treated digestate returns nutrients to agricultural production.'],['Forage & feed','Forage and feed return to livestock production, completing the cycle.']
];
